server:
  port: 8080
  # servlet:
  #   context-path: /api  # Comment out or remove to test without context path

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Blood;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    open-in-view: false  # Disable OpenEntityManagerInViewInterceptor